definitions:
  dto.CreateFacetInput:
    properties:
      color:
        type: string
      configuration:
        $ref: '#/definitions/json.FacetConfig'
      privateLabel:
        type: string
      publicLabel:
        type: string
    required:
    - color
    - configuration
    - privateLabel
    - publicLabel
    type: object
  dto.CreateFacetResponse:
    properties:
      color:
        type: string
      configuration:
        $ref: '#/definitions/json.FacetConfig'
      createdAt:
        type: string
      id:
        type: integer
      privateLabel:
        type: string
      publicLabel:
        type: string
    type: object
  dto.CreateUserCommunicationServiceInput:
    properties:
      name:
        type: string
      service:
        type: string
      value:
        type: string
    required:
    - name
    - service
    - value
    type: object
  dto.CreateUserCommunicationServiceResponse:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      service:
        $ref: '#/definitions/enum.CommunicationService'
      value:
        type: string
    type: object
  dto.GetFacetResponseItem:
    properties:
      color:
        type: string
      configuration:
        $ref: '#/definitions/json.FacetConfig'
      createdAt:
        type: string
      id:
        type: integer
      privateLabel:
        type: string
      publicLabel:
        type: string
    type: object
  dto.GetUserByEmailResponse:
    properties:
      avatarUrl:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  dto.GetUserCommunicationServicesResponseItem:
    properties:
      id:
        type: integer
      name:
        type: string
      service:
        $ref: '#/definitions/enum.CommunicationService'
      value:
        type: string
    type: object
  dto.GetUserMeResponse:
    properties:
      avatarUrl:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  dto.UpdateUserCommunicationServiceInput:
    properties:
      name:
        type: string
      serviceType:
        $ref: '#/definitions/enum.CommunicationService'
      value:
        type: string
    type: object
  dto.UpdateUserCommunicationServiceResponse:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      service:
        $ref: '#/definitions/enum.CommunicationService'
      value:
        type: string
    type: object
  enum.CommunicationService:
    enum:
    - face-to-face
    - phone
    - message
    - email
    - discord
    - microsoft-teams
    type: string
    x-enum-varnames:
    - FaceToFace
    - Phone
    - Message
    - Email
    - Discord
    - MicrosoftTeams
  enum.FacetStatus:
    enum:
    - available
    - emergency-only
    type: string
    x-enum-varnames:
    - Available
    - EmergencyOnly
  error.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  json.FacetConfig:
    properties:
      items:
        items:
          $ref: '#/definitions/json.FacetConfigItem'
        type: array
    type: object
  json.FacetConfigItem:
    properties:
      id:
        type: integer
      status:
        $ref: '#/definitions/enum.FacetStatus'
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the backend API for the HS project
  title: HS Backend API
  version: "1.0"
paths:
  /api/facets:
    get:
      consumes:
      - application/json
      description: Returns facets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.GetFacetResponseItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get facets
      tags:
      - Facets
    post:
      consumes:
      - application/json
      description: Creates a new facet
      parameters:
      - description: Facet
        in: body
        name: facet
        required: true
        schema:
          $ref: '#/definitions/dto.CreateFacetInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateFacetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create facet
      tags:
      - Facets
  /api/users:
    get:
      consumes:
      - application/json
      description: Returns user info by email query param
      parameters:
      - description: Email address
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetUserByEmailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user by email
      tags:
      - Users
  /api/users/communication-services:
    get:
      consumes:
      - application/json
      description: Returns user communication services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.GetUserCommunicationServicesResponseItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user communication services
      tags:
      - User Communication Services
    post:
      consumes:
      - application/json
      description: Creates a new user communication service
      parameters:
      - description: User Communication Service
        in: body
        name: userCommunicationService
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserCommunicationServiceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateUserCommunicationServiceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create user communication service
      tags:
      - User Communication Services
  /api/users/communication-services/{userCommunicationServiceId}:
    delete:
      consumes:
      - application/json
      description: Deletes a user communication service
      parameters:
      - description: User Communication Service ID
        in: path
        name: userCommunicationServiceId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete user communication service
      tags:
      - User Communication Services
    patch:
      consumes:
      - application/json
      description: Updates a user communication service
      parameters:
      - description: User Communication Service ID
        in: path
        name: userCommunicationServiceId
        required: true
        type: integer
      - description: User Communication Service
        in: body
        name: userCommunicationService
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserCommunicationServiceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateUserCommunicationServiceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user communication service
      tags:
      - User Communication Services
  /api/users/me:
    get:
      consumes:
      - application/json
      description: Returns user me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetUserMeResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user me
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and your token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
